Adding Kubernetes events support and events for various operations. #KO-48
aerospike/aerospike-kubernetes-operator pull request #133
Opened 2022-05-25 06:14 UTC by tanmayja

2022-08-12 08:37 UTC, sud82 requested changes

2022-08-12 08:37 UTC, sud82 commented on controllers/reconciler.go
> +			fmt.Sprintf("Failed to update AerospikeCluster status %s/%s", r.aeroCluster.Namespace, r.aeroCluster.Name))
Check the above events. Use either cluster or AerospikeCluster

2022-08-12 08:37 UTC, sud82 commented on controllers/statefulset.go
> +			"Already existed configmap is same as current configmap, so no change required",
This log may become very frequent.
I think we can remove this log and add the log only if configMap is getting updated.

2022-08-12 08:43 UTC, sud82 commented on controllers/rack.go
> +	r.Recorder.Event(r.aeroCluster, corev1.EventTypeNormal, "RackScaleDown",
It's better to place this event and the above log when scale down is needed. Basically after this condition
`if *found.Spec.Replicas <= desiredSize {
		return found, reconcileSuccess()
	}`

2022-08-12 09:33 UTC, tanmayja commented on controllers/reconciler.go
> +				fmt.Sprintf("Deleted cluster %s/%s", r.aeroCluster.Namespace, r.aeroCluster.Name))
using AerospikeCluster now

2022-08-12 10:57 UTC, sud82 approved these changes

2022-08-16 13:36 UTC, ashishshinde approved these changes

2022-08-16 13:39 UTC, merged