[KO-111] Adding script to collect logs of Aerospike cluster
aerospike/aerospike-kubernetes-operator pull request #146
Opened 2022-08-16 18:46 UTC by tanmayja

2022-08-22 18:23 UTC, arrowplum requested changes
I think scraper not scrapper.

2022-08-23 04:43 UTC, tanmayja commented
> I think scraper not scrapper.

Done!

2022-09-15 20:09 UTC, arrowplum approved these changes

2023-02-10 09:36 UTC, sud82 commented
This will be converted to a tool and will be added in a different repo.

2023-02-10 09:36 UTC, closed without merging