adding named port in load balancer service.
aerospike/aerospike-kubernetes-operator pull request #227
Opened 2023-06-23 17:13 UTC by tanmayja

2023-06-23 17:33 UTC, abhishekdwivedi3060 requested changes

2023-06-23 17:33 UTC, abhishekdwivedi3060 commented on config/crd/bases/asdb.aerospike.com_aerospikeclusters.yaml
> +                      portName:
Update helm-chart CRD as well

2023-06-23 17:47 UTC, abhishekdwivedi3060 approved these changes

2023-06-26 08:22 UTC, sud82 approved these changes

2023-06-26 08:23 UTC, merged