K0-314: Added support for batch scale-down
aerospike/aerospike-kubernetes-operator pull request #279
Opened 2024-03-25 06:50 UTC by abhishekdwivedi3060

2024-04-10 10:10 UTC, tanmayja commented on controllers/rack.go
>  	// No need for these checks if pod was not running.
can change comments like pod -> pods etc..

2024-04-12 05:28 UTC, tanmayja approved these changes

2024-04-12 06:59 UTC, sud82 requested changes

2024-04-12 06:59 UTC, sud82 commented on test/batch_scaledown_pods_test.go
> +func isBatchScaleDown(aeroCluster *asdbv1.AerospikeCluster, scaleDownBatchSize int) bool {
Review this.

2024-04-17 08:25 UTC, merged