[KO-321] [KO-320] Added a flag to disable PDB
aerospike/aerospike-kubernetes-operator pull request #286
Opened 2024-04-24 12:48 UTC by sud82

Added tests for disablePDB flag

2024-04-25 05:48 UTC, tanmayja commented on test/poddisruptionbudget_test.go
> +		defaultMaxUpavailable := intstr.FromInt(1)
spelling

2024-04-25 05:48 UTC, tanmayja commented on controllers/poddistruptionbudget.go
Certainly, adding a label to the PDB (Pod Disruption Budget) created by the operator can be a helpful approach to distinguish it from those created by users, especially if they share the same name as the cluster. This labeling practice can prevent accidental interference with user-created PDBs and ensure clarity in management and troubleshooting processes.

2024-04-29 06:46 UTC, abhishekdwivedi3060 requested changes

2024-04-29 06:46 UTC, abhishekdwivedi3060 commented on controllers/poddistruptionbudget.go
> +	return r.Client.Delete(context.TODO(), pdb)
We don't have to actually do get opertion. We can directly call delete and ignore isNotFound error.

2024-04-29 06:46 UTC, abhishekdwivedi3060 commented on test/poddisruptionbudget_test.go
> +				validatePDB(ctx, aeroCluster, 1)
```suggestion
				validatePDB(ctx, aeroCluster, defaultMaxUpavailable.IntValue())
```

2024-04-29 06:46 UTC, abhishekdwivedi3060 commented on test/poddisruptionbudget_test.go
> +				validatePDB(ctx, aeroCluster, 1)
```suggestion
				validatePDB(ctx, aeroCluster, defaultMaxUpavailable.IntValue())
```

2024-04-30 08:12 UTC, tanmayja approved these changes

2024-05-03 04:13 UTC, abhishekdwivedi3060 approved these changes

2024-05-03 10:41 UTC, merged