[KO-326] Added support for default-password-file
aerospike/aerospike-kubernetes-operator pull request #289
Opened 2024-05-17 06:33 UTC by sud82

2024-05-17 06:55 UTC, sud82 commented on controllers/client_policy.go
> +	secretName := volume.Source.Secret.SecretName
Validate if it's secret or not.

2024-05-17 07:09 UTC, sud82 commented on test/cluster_helper.go
> +					"security": map[string]interface{}{
This func is used in pre-7.1.0 clusters as well. This field is not valid for them. Create another func.

2024-05-17 07:14 UTC, sud82 commented on test/access_control_test.go
> +					nodes := client.GetNodeNames()
What if 3 min not enough. Can we use client.IsConnected?

2024-05-17 10:31 UTC, abhishekdwivedi3060 requested changes

2024-05-17 10:31 UTC, abhishekdwivedi3060 commented on api/v1/aerospikecluster_validating_webhook.go
> +	if defaultPassFilePath != nil {
We can add a condition here to error out in case of secret agent default password file path

2024-05-20 08:35 UTC, tanmayja reviewed
change  AKO version from crd annotation in file api/v1/aerospikecluster_types.go:927

2024-05-20 10:14 UTC, abhishekdwivedi3060 approved these changes
Are we going to create a separate PR for 3.0.0 tag update across repo?

2024-05-20 11:58 UTC, merged