Montoring stack
aerospike/aerospike-kubernetes-operator pull request #300
Opened 2024-07-08 18:15 UTC by tanmayja

A consolidated example to setup full monitoring stack(grafana dashboards, prometheus and alert manager).

2024-08-12 16:15 UTC, abhishekdwivedi3060 commented on config/monitoring/alertmanager/service.yaml
> +    app: aerospike-monitoring-stack-alertmanager
This selector doesn't match with STS pods

2024-08-12 16:24 UTC, abhishekdwivedi3060 commented on config/monitoring/alertmanager/kustomization.yaml
> +      app.kubernetes.io/component: aerospike-alertmanager
If we are defining this section, we don't have to add this label in all the resource yamls individually. 
It'll be easy to change from one place. 
Do this change for all the components wherever applicable

2024-08-13 09:55 UTC, sud82 requested changes

2024-08-13 09:55 UTC, sud82 commented on config/monitoring/prometheus/statefulset.yaml
> +          resources:
No need for empty object

2024-08-13 09:55 UTC, sud82 commented on config/monitoring/prometheus/statefulset.yaml
> +apiVersion: apps/v1
Check comments from the previous STSs

2024-08-13 14:13 UTC, tanmayja commented on config/monitoring/alertmanager/statefulset.yaml
> +    unique-app: aerospike-monitoring-stack-alertmanager
removed already.

2024-08-13 14:24 UTC, tanmayja commented on config/monitoring/grafana/statefulset.yaml
> +            - name: cluster-dashboard
when created single configmap, faces the max size issue. Hence created separate mounts.

2024-08-13 14:39 UTC, tanmayja commented on config/monitoring/alertmanager/statefulset.yaml
> +        fsGroup: 26
runAsNonRoot is not allowed in any of 3 components.
alertmanager error:
`Error: container has runAsNonRoot and image has non-numeric user (nobody), cannot verify user is non-root (pod: "aerospike-monitoring-stack-alertmanager-0_monitoring(4b639449-8ae7-4fd8-9aa3-83abe7b2d41d)", container: alertmanager)`

2024-08-14 05:57 UTC, tanmayja commented on config/monitoring/alertmanager/statefulset.yaml
> +  selector: {}
selectors will be populated by kustomization.
```
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: aerospike-alertmanager
      app: aerospike-monitoring-stack-alertmanager
```

2024-08-27 10:21 UTC, abhishekdwivedi3060 approved these changes

2024-08-28 09:43 UTC, sud82 approved these changes

2024-08-28 13:44 UTC, tanmayja commented on config/monitoring/grafana/statefulset.yaml
> +        fsGroup: 472
It is needed to set fsgroup as current user in grafana is uid=472(grafana) and we get error
Error: ✗ failed to connect to database: mkdir /data/grafana: permission denied

2024-08-28 15:04 UTC, merged