Adding missing fields in aerospike-cluster-cr.yaml
aerospike/aerospike-kubernetes-operator pull request #306
Opened 2024-07-29 08:09 UTC by tanmayja

2024-07-29 09:06 UTC, abhishekdwivedi3060 requested changes

2024-07-29 09:06 UTC, abhishekdwivedi3060 commented on helm-charts/aerospike-cluster/templates/aerospike-cluster-cr.yaml
> +  maxUnavailable: {{ .Values.maxUnavailable }}
We should add all these new fields in values.yaml for visibility

2024-07-31 10:36 UTC, abhishekdwivedi3060 commented on helm-charts/aerospike-cluster/templates/aerospike-cluster-cr.yaml
> +  {{- end }}
This won't give the correct output, use something like
```
  {{- with .Values.k8sNodeBlockList }}
  k8sNodeBlockList:
  {{- toYaml . | nindent 4 }}
  {{- end }}
```

2024-07-31 10:36 UTC, abhishekdwivedi3060 commented on helm-charts/aerospike-cluster/values.yaml
> +  - <node-name>
```suggestion
rosterNodeBlockList: []
#  - <aerospike-node-id>

## k8sNodeBlockList is a list of Kubernetes nodes which are not used for Aerospike pods.
## Replace the value with kubernetes cluster node name which needs to be blocked.
k8sNodeBlockList: []
#  - <node-name>
```

2024-07-31 10:36 UTC, abhishekdwivedi3060 commented on helm-charts/aerospike-cluster/templates/aerospike-cluster-cr.yaml
> +  maxUnavailable: {{ .Values.maxUnavailable }}
Add comments for all the new fields added in this file

2024-08-01 05:47 UTC, abhishekdwivedi3060 approved these changes

2024-08-09 04:43 UTC, sud82 approved these changes

2024-08-09 04:44 UTC, merged