[KO-335] Adding support for HPA
aerospike/aerospike-kubernetes-operator pull request #307
Opened 2024-08-06 06:39 UTC by tanmayja

https://aerospike.atlassian.net/wiki/spaces/KO/pages/3593338906/Horizontal+Pod+Autoscaler

2024-08-13 08:50 UTC, abhishekdwivedi3060 commented on api/v1/aerospikecluster_types.go
> +//+kubebuilder:subresource:scale:specpath=.spec.size,statuspath=.status.size,selectorpath=.status.selector
```suggestion
// +kubebuilder:subresource:scale:specpath=.spec.size,statuspath=.status.size,selectorpath=.status.selector
```

2024-10-01 08:08 UTC, sud82 commented
Will be merged in next release.

2025-01-02 06:51 UTC, sud82 requested changes

2025-01-02 06:51 UTC, sud82 commented on api/v1/aerospikecluster_types.go
> +	Selector string                `json:"selector"`
Why selector is not omitempty? Will it not cause the issue during the upgrade?

2025-01-02 06:51 UTC, sud82 commented on test/cluster/autoscaling_test.go
> +	"golang.org/x/net/context"
Remove this context import.

2025-01-02 06:51 UTC, sud82 commented on test/cluster/autoscaling_test.go
> +				).Should(Equal(int32(3)))
Verify if labels are present in the status subresource.

2025-01-02 06:51 UTC, sud82 commented on test/cluster/autoscaling_test.go
> +				// Testing over upgrade as it is a long-running operation
Remove this comment.

2025-01-02 07:47 UTC, abhishekdwivedi3060 commented on api/v1/aerospikecluster_types.go
> +	Selector string                `json:"selector"`
Yeah, it'll fail in CR validation against new CRDs during upgrade.
Making it omitempty

2025-01-02 08:54 UTC, abhishekdwivedi3060 commented on test/cluster/autoscaling_test.go
> +				).Should(Equal(int32(3)))
Added a generic check for all clusters

2025-01-02 09:11 UTC, sud82 approved these changes

2025-01-02 09:13 UTC, merged