KO-348: Skip setting hostPort in Aerospike container for podOnly network and multiPodPerHost: false
aerospike/aerospike-kubernetes-operator pull request #316
Opened 2024-10-01 08:06 UTC by jwalantmodi05

Skip setting hostPort in Aerospike container for podOnly network and multiPodPerHost: false

2024-10-04 06:19 UTC, sud82 requested changes

2024-10-04 06:19 UTC, sud82 commented on test/cluster/network_policy_test.go
> +		for _, port := range ports {
These are full integration tests. Therefore, you should try to deploy the cluster with podOnly network and then check if hostPort is exposed or not.

2024-10-04 06:19 UTC, sud82 commented on test/cluster/network_policy_test.go
> +		for _, port := range ports {
No need to make GetSTSContainerPort public

2024-10-15 00:23 UTC, tanmayja approved these changes

2024-10-15 01:18 UTC, sud82 approved these changes

2024-10-15 01:21 UTC, merged