KO-341: Added event flow for BackupService, Backup and Restore controllers
aerospike/aerospike-kubernetes-operator pull request #324
Opened 2024-11-12 12:12 UTC by jwalantmodi05

2024-11-29 09:23 UTC, tanmayja reviewed
We should enhance event tracking by incorporating additional events, especially for the successful (happy path) scenarios. Currently, only failure and deletion events are being logged, leaving gaps in visibility for standard operations.

2024-12-26 14:26 UTC, abhishekdwivedi3060 requested changes

2024-12-26 14:26 UTC, abhishekdwivedi3060 commented on internal/controller/restore/reconciler.go
> +		r.Recorder.Eventf(r.aeroRestore, corev1.EventTypeWarning, "CheckStatusFailed",
```suggestion
		r.Recorder.Eventf(r.aeroRestore, corev1.EventTypeWarning, "RestoreStatusCheckFailed",
```

2024-12-26 14:26 UTC, abhishekdwivedi3060 commented on internal/controller/restore/reconciler.go
> +		"Restore status: %+v", restoreStatus)
Seems too much info for event. Better not to add in events.
Instead add Restore Compete event in the main reconcile func at the very end https://github.com/aerospike/aerospike-kubernetes-operator/pull/324/files#diff-47218f09e6b90f3189bfd8f3e13c64f77d5ac7bf48c9039ff21ee499ff944f33R73

2025-01-02 09:30 UTC, jwalantmodi05 commented on internal/controller/restore/reconciler.go
> +		"Restore status: %+v", restoreStatus)
Okay, I will remove this event and will add restore complete event.

2025-01-03 17:16 UTC, abhishekdwivedi3060 approved these changes

2025-01-06 05:15 UTC, merged