KO-358: Enhance AerospikeBackupService CR with all the possible deployment configuration params
aerospike/aerospike-kubernetes-operator pull request #328
Opened 2024-12-18 11:02 UTC by jwalantmodi05

2025-01-02 10:41 UTC, abhishekdwivedi3060 requested changes

2025-01-02 10:41 UTC, abhishekdwivedi3060 commented on test/backup_service/backup_service_test.go
>  				limitMem := resource.MustParse("2Gi")
Reduce the memory request and cpu. 
It might cause issue while running tests on local dev clusters

2025-01-06 07:38 UTC, jwalantmodi05 commented on test/backup_service/backup_service_test.go
>  				limitMem := resource.MustParse("2Gi")
Okay, I will reduce it.

2025-01-08 07:54 UTC, abhishekdwivedi3060 approved these changes

2025-01-09 09:03 UTC, tanmayja approved these changes

2025-01-10 05:51 UTC, merged