Support TLS configuration of AerospikeCluster Client through env variables.
aerospike/aerospike-kubernetes-operator pull request #46
Opened 2021-06-29 16:17 UTC by skolosov-snap

Feeding Client Certs to the operator through env. variables.
New logic is following:

If env. variables are set then reading certs/key from the files, otherwise, read them from the secret.
This should be reloadable since operator does not store/cache certs or AS client connections.

Also validation added to make sure tls-authenticate-client contains name (CN or DNS from SAN) from operator's cert if configured.

2021-07-14 16:19 UTC, arrowplum commented
Discussions have been continuing in Slack channel.

2021-07-15 17:49 UTC, skolosov-snap reviewed
> Discussions have been continuing in Slack channel.

@arrowplum, I'm not in this discussion. The last update on a slack was week ago. Is there any other thread for this discussion I'm not aware of?

2021-07-15 17:54 UTC, sud82 requested changes

2021-07-15 17:54 UTC, sud82 commented on api/v1alpha1/aerospikecluster_types.go
> +	SecretName *string `json:"secretName,omitempty"`
secretName and namespace can be put in a struct like secretSource. CertSource should be like 
```
CertSource {
  *source1
  *source2
  *source3
}
```
In the future, we may also like to add some more fields inside any source. For e.g. I suggested the below schema for secret, not sure if you missed it or deliberately decided to skip it

```
type AerospikeSecretCertSource struct {
    SecretName string `json:"secretName"`
	CaCertsFilename    string `json:"caCertFilename"`
	// +optional
	ClientCertFilename string `json:"clientCertFilename"`
	// +optional
	ClientKeyFilename  string `json:"clientKeyFilename"`
}
```
ClientCertFilename, ClientKeyFilename are optional if tls-authenticate-client is "any"
https://docs.aerospike.com/docs/reference/configuration/#tls-authenticate-client

2021-07-16 03:21 UTC, skolosov-snap reviewed
I believe when tls-authenticate-client is "any" then client cert still needs to be used. because it's still mTLS but Aerospike server just doesn't validate name provided in client cert.

New logic is following:
- if tls-authenticate-client is "false", then we do not require to provide client cert, however you still can provide CA certs.
- tls-authenticate-client is "any", then client cert has to be provided, but you don't need to provide tlsClientName
- otherwise you have to provide both client cert and tlsClientName (which will be added to tls-authenticate-client if missed)

2021-07-16 03:21 UTC, skolosov-snap commented on api/v1alpha1/aerospikecluster_validating_webhook.go
> +	}
Nice catch. Refactored.

2021-07-16 14:04 UTC, sud82 requested changes

2021-07-16 17:26 UTC, skolosov-snap commented on api/v1alpha1/aerospikecluster_types.go
> +	// +optional
Yes, caCertsPath is optional. If it's omitted then system CA certs are used by default.

2021-07-16 17:34 UTC, skolosov-snap commented on api/v1alpha1/aerospikecluster_types.go
> +}
SecretCertSource.ClientCertFilename and ertPathInOperator.ClientCertPath are optional. You can use Sources to configure CA certs only (i.e. when tls-authenticate-client is "false"). Moreover, we have a validation which checks that exactly one of these two are not nil (see next method, first check). So "(c.SecretCertSource != nil || c.CertPathInOperator != nil )" will always be true.

2021-07-17 00:46 UTC, skolosov-snap commented
Fixed tests.

2021-07-19 11:47 UTC, sud82 approved these changes

2021-07-19 11:48 UTC, merged